package com.example.stickhero.Code;

public class Stick {

    private static int width; // what do we initialise this to??

    public void rotateStick(){
        // rotates the stick generated by stick-hero
    }

    public static int getWidth() {
        return width;
    }

    public static void setWidth(int width) {
        Stick.width = width;
    }
}
