package com.example.stickhero;

public class Stick extends Block {


    public Stick(double height, double width, double x, double y) {
        super(height, 5, x, y);
    }

    public void rotateStick(){
        // rotates the stick generated by stick-hero
    }

}
